fd.model.ImageMng = {
	init: function( evt ) {
		this._oModel = new sap.ui.model.json.JSONModel();
		this._oModel.setSizeLimit(1000);
		this._oModel.setData( this._mIcons );
	},

	getControlIcon: function(controlName) {
		if (controlName.sapStartWith("sap.m")) {
			if (this._mControlIcon["sap.m"].indexOf(controlName) !== -1) {
				return "./images/sap.m/" + controlName + ".png";
			}

		}
		return "";
	},

	openIconDialog: function( funcCallBack, cbContext, openByControl, cbData ) {
	    if (!this._oIconDlg) {
			this._oIconDlg = sap.ui.xmlfragment(this.iconPrefixId, "fd.view.fragments.IconMng", this);
			this._oIconDlg.setModel( this._oModel);
		}

		//save the context used for call back
		this._funcCallBack = funcCallBack;
		this._cbContext = cbContext;
		this._cbData  = cbData;

		this._oIconDlg.openBy( openByControl);
	},

	onLiveSearch: function(evt) {
		var searchValue = this.byId("search").getValue();
		var bShowSearchList = searchValue.length !== 0;

		var searchList = this.byId("searchIconList");
		searchList.setVisible( bShowSearchList);
		this.byId("groupList").setVisible( !bShowSearchList);

		var binding = searchList.getBinding("items");
		if (bShowSearchList && binding ) {
			var filterName = new sap.ui.model.Filter("name", sap.ui.model.FilterOperator.Contains, searchValue);
			binding.filter([filterName]);
		}
	},

	/**
	 * Just show the page to  iconPage and set the binding context
	 * @param  {[type]} evt [description]
	 * @return {[type]}     [description]
	 */
	onGroupListItemPressed: function( evt ) {
	    this.byId("navContainer").to( this.byId("iconPage"));
	    var iconList  = this.byId("iconList");
	    iconList.bindContext( evt.getSource().getBindingContext().getPath());
	},
	
	onIconListItemPressed: function( evt ) {
		//select one item, then need icon name and call the call back
	    this._oIconDlg.close();
	},
	
	//?? later need check why the list itemPress event can work, but the ListItem pressed evetn not work
	onIconItemPressed: function( evt ) {
		var item = evt.getParameter("listItem");
		if (item) {
			var iconUrl = item.getIcon();
			this._funcCallBack.call( this._cbContext, iconUrl, this._cbData);
		}
		this._oIconDlg.close();
	},
	

	onNavBack: function( evt ) {
	    this.byId("navContainer").back();
	},
	
	
	byId: function(id) {
		var wholeId = this.iconPrefixId + "--" + id;
		return sap.ui.getCore().byId(wholeId);
	},

	
	iconPrefixId: "FDIconMng",

	_mControlIcon: {
		"sap.m": [
			"sap.m.ActionListItem",
			"sap.m.Bar",
			"sap.m.Button",
			"sap.m.Carousel",
			"sap.m.CheckBox",
			"sap.m.CustomListItem",
			"sap.m.CustomTile",
			"sap.m.DatePicker",
			"sap.m.DateTimeInput",
			"sap.m.DisplayListItem",
			"sap.m.FeedListItem",
			"sap.m.Grid",
			"sap.m.GroupHeaderList",
			"sap.m.GroupHeaderListItem",
			"sap.m.GrowingList",
			"sap.m.HBox",
			"sap.m.IconTabBar",
			"sap.m.IconTabFilter",
			"sap.m.Image",
			"sap.m.Input",
			"sap.m.InputListItem",
			"sap.m.Label",
			"sap.m.Link",
			"sap.m.List",
			"sap.m.ListItem",
			"sap.m.ObjectAttribute",
			"sap.m.ObjectHeader",
			"sap.m.ObjectIdentifier",
			"sap.m.ObjectListItem",
			"sap.m.ObjectNumber",
			"sap.m.ObjectStatus",
			"sap.m.Page",
			"sap.m.Panel",
			"sap.m.ProgressIndicator",
			"sap.m.PullToRefresh",
			"sap.m.RadioButton",
			"sap.m.Rating.Indicator",
			"sap.m.RatingIndicator",
			"sap.m.ResponsiveForm",
			"sap.m.ScrollContainer",
			"sap.m.SearchField",
			"sap.m.SegmentedButton",
			"sap.m.Select",
			"sap.m.Slider",
			"sap.m.StandardListItem",
			"sap.m.StandardTile",
			"sap.m.Switch",
			"sap.m.Text",
			"sap.m.TextArea",
			"sap.m.TextField",
			"sap.m.TileContainer",
			"sap.m.Title",
			"sap.m.Toolbar",
			"sap.m.ToolbarSpacer",
			"sap.m.VBox",
			"sap.me.ProgressIndicator",
			"sap.me.TabContainer",
			"_sap.me.OverlayCalendar"
		]
	},

	_mIcons: {
		"groups": [{
			"name": "all",
			"text": "All",
			"icons": [{
				"name": "accelerated"
			}, {
				"name": "accept"
			}, {
				"name": "accidental-leave"
			}, {
				"name": "account"
			}, {
				"name": "accounting-document-verification"
			}, {
				"name": "action"
			}, {
				"name": "action-settings"
			}, {
				"name": "activate"
			}, {
				"name": "activities"
			}, {
				"name": "activity-2"
			}, {
				"name": "activity-assigned-to-goal"
			}, {
				"name": "activity-individual"
			}, {
				"name": "activity-items"
			}, {
				"name": "add"
			}, {
				"name": "add-activity"
			}, {
				"name": "add-activity-2"
			}, {
				"name": "add-contact"
			}, {
				"name": "add-coursebook"
			}, {
				"name": "add-equipment"
			}, {
				"name": "add-favorite"
			}, {
				"name": "add-filter"
			}, {
				"name": "add-photo"
			}, {
				"name": "add-process"
			}, {
				"name": "add-product"
			}, {
				"name": "address-book"
			}, {
				"name": "addresses"
			}, {
				"name": "alert"
			}, {
				"name": "along-stacked-chart"
			}, {
				"name": "alphabetical-order"
			}, {
				"name": "appointment"
			}, {
				"name": "appointment-2"
			}, {
				"name": "approvals"
			}, {
				"name": "area-chart"
			}, {
				"name": "arobase"
			}, {
				"name": "arrow-bottom"
			}, {
				"name": "arrow-down"
			}, {
				"name": "arrow-left"
			}, {
				"name": "arrow-right"
			}, {
				"name": "arrow-top"
			}, {
				"name": "attachment"
			}, {
				"name": "attachment-audio"
			}, {
				"name": "attachment-e-pub"
			}, {
				"name": "attachment-html"
			}, {
				"name": "attachment-photo"
			}, {
				"name": "attachment-text-file"
			}, {
				"name": "attachment-video"
			}, {
				"name": "attachment-zip-file"
			}, {
				"name": "back-to-top"
			}, {
				"name": "background"
			}, {
				"name": "badge"
			}, {
				"name": "bar-chart"
			}, {
				"name": "bar-code"
			}, {
				"name": "basket"
			}, {
				"name": "batch-payments"
			}, {
				"name": "bbyd-active-sales"
			}, {
				"name": "bbyd-dashboard"
			}, {
				"name": "bed"
			}, {
				"name": "begin"
			}, {
				"name": "blank-tag"
			}, {
				"name": "blank-tag-2"
			}, {
				"name": "bo-strategy-management"
			}, {
				"name": "bookmark"
			}, {
				"name": "border"
			}, {
				"name": "bubble-chart"
			}, {
				"name": "building"
			}, {
				"name": "burglary"
			}, {
				"name": "bus-public-transport"
			}, {
				"name": "business-by-design"
			}, {
				"name": "business-card"
			}, {
				"name": "business-objects-experience"
			}, {
				"name": "business-objects-explorer"
			}, {
				"name": "business-objects-mobile"
			}, {
				"name": "business-one"
			}, {
				"name": "calendar"
			}, {
				"name": "camera"
			}, {
				"name": "cancel-maintenance"
			}, {
				"name": "capital-projects"
			}, {
				"name": "car-rental"
			}, {
				"name": "card"
			}, {
				"name": "cargo-train"
			}, {
				"name": "cart"
			}, {
				"name": "cart-2"
			}, {
				"name": "cart-3"
			}, {
				"name": "cart-4"
			}, {
				"name": "cart-5"
			}, {
				"name": "cart-approval"
			}, {
				"name": "cart-full"
			}, {
				"name": "cause"
			}, {
				"name": "chain-link"
			}, {
				"name": "chalkboard"
			}, {
				"name": "chart-axis"
			}, {
				"name": "Chart-Tree-Map"
			}, {
				"name": "check-availability"
			}, {
				"name": "choropleth-chart"
			}, {
				"name": "citizen-connect"
			}, {
				"name": "clinical-order"
			}, {
				"name": "clinical-tast-tracker"
			}, {
				"name": "close-command-field"
			}, {
				"name": "collaborate"
			}, {
				"name": "collapse"
			}, {
				"name": "collapse-group"
			}, {
				"name": "collections-insight"
			}, {
				"name": "collections-management"
			}, {
				"name": "collision"
			}, {
				"name": "color-fill"
			}, {
				"name": "column-chart-dual-axis"
			}, {
				"name": "comment"
			}, {
				"name": "commission-check"
			}, {
				"name": "company-view"
			}, {
				"name": "compare"
			}, {
				"name": "compare-2"
			}, {
				"name": "competitor"
			}, {
				"name": "complete"
			}, {
				"name": "connected"
			}, {
				"name": "contacts"
			}, {
				"name": "course-book"
			}, {
				"name": "course-program"
			}, {
				"name": "create"
			}, {
				"name": "create-entry-time"
			}, {
				"name": "create-leave-request"
			}, {
				"name": "create-session"
			}, {
				"name": "credit-card"
			}, {
				"name": "crm-sales"
			}, {
				"name": "crm-service-manager"
			}, {
				"name": "crop"
			}, {
				"name": "crossed-line-chart"
			}, {
				"name": "curriculum"
			}, {
				"name": "customer"
			}, {
				"name": "customer-and-contacts"
			}, {
				"name": "customer-and-supplier"
			}, {
				"name": "customer-briefing"
			}, {
				"name": "customer-financial-fact-sheet"
			}, {
				"name": "customer-history"
			}, {
				"name": "customer-order-entry"
			}, {
				"name": "customer-view"
			}, {
				"name": "database"
			}, {
				"name": "decision"
			}, {
				"name": "decline"
			}, {
				"name": "delete"
			}, {
				"name": "detail-view"
			}, {
				"name": "dimension"
			}, {
				"name": "disconnected"
			}, {
				"name": "discussion"
			}, {
				"name": "discussion-2"
			}, {
				"name": "dishwasher"
			}, {
				"name": "display"
			}, {
				"name": "display-more"
			}, {
				"name": "doc-attachment"
			}, {
				"name": "doctor"
			}, {
				"name": "document"
			}, {
				"name": "document-text"
			}, {
				"name": "documents"
			}, {
				"name": "down"
			}, {
				"name": "download"
			}, {
				"name": "draw-rectangle"
			}, {
				"name": "drill-down"
			}, {
				"name": "drill-up"
			}, {
				"name": "drop-down-list"
			}, {
				"name": "dropdown"
			}, {
				"name": "duplicate"
			}, {
				"name": "e-care"
			}, {
				"name": "e-learning"
			}, {
				"name": "eam-work-order"
			}, {
				"name": "edit"
			}, {
				"name": "edit-outside"
			}, {
				"name": "education"
			}, {
				"name": "electrocardiogram"
			}, {
				"name": "electronic-medical-record"
			}, {
				"name": "email"
			}, {
				"name": "email-read"
			}, {
				"name": "employee"
			}, {
				"name": "employee-approvals"
			}, {
				"name": "employee-lookup"
			}, {
				"name": "employee-pane"
			}, {
				"name": "employee-rejections"
			}, {
				"name": "end-user-experience-monitoring"
			}, {
				"name": "endoscopy"
			}, {
				"name": "energy-saving-lightbulb"
			}, {
				"name": "enter-more"
			}, {
				"name": "eraser"
			}, {
				"name": "error"
			}, {
				"name": "example"
			}, {
				"name": "excel-attachment"
			}, {
				"name": "exit-full-screen"
			}, {
				"name": "expand"
			}, {
				"name": "expand-group"
			}, {
				"name": "expense-report"
			}, {
				"name": "explorer"
			}, {
				"name": "factory"
			}, {
				"name": "fallback"
			}, {
				"name": "family-care"
			}, {
				"name": "family-protection"
			}, {
				"name": "favorite"
			}, {
				"name": "favorite-list"
			}, {
				"name": "fax-machine"
			}, {
				"name": "feed"
			}, {
				"name": "feeder-arrow"
			}, {
				"name": "filter"
			}, {
				"name": "flag"
			}, {
				"name": "flight"
			}, {
				"name": "fob-watch"
			}, {
				"name": "folder"
			}, {
				"name": "folder-blank"
			}, {
				"name": "folder-full"
			}, {
				"name": "form"
			}, {
				"name": "forward"
			}, {
				"name": "fridge"
			}, {
				"name": "full-screen"
			}, {
				"name": "full-stacked-chart"
			}, {
				"name": "full-stacked-column-chart"
			}, {
				"name": "functional-location"
			}, {
				"name": "future"
			}, {
				"name": "gantt-bars"
			}, {
				"name": "general-leave-request"
			}, {
				"name": "generate-shortcut"
			}, {
				"name": "geographic-bubble-chart"
			}, {
				"name": "globe"
			}, {
				"name": "goal"
			}, {
				"name": "goalseek"
			}, {
				"name": "grid"
			}, {
				"name": "group"
			}, {
				"name": "group-2"
			}, {
				"name": "header"
			}, {
				"name": "heating-cooling"
			}, {
				"name": "hello-world"
			}, {
				"name": "hide"
			}, {
				"name": "hint"
			}, {
				"name": "history"
			}, {
				"name": "home"
			}, {
				"name": "home-share"
			}, {
				"name": "horizontal-bar-chart"
			}, {
				"name": "horizontal-bar-chart-2"
			}, {
				"name": "horizontal-grip"
			}, {
				"name": "horizontal-stacked-chart"
			}, {
				"name": "hr-approval"
			}, {
				"name": "idea-wall"
			}, {
				"name": "image-viewer"
			}, {
				"name": "inbox"
			}, {
				"name": "incident"
			}, {
				"name": "incoming-call"
			}, {
				"name": "initiative"
			}, {
				"name": "inspect"
			}, {
				"name": "inspect-down"
			}, {
				"name": "inspection"
			}, {
				"name": "instance"
			}, {
				"name": "insurance-car"
			}, {
				"name": "insurance-house"
			}, {
				"name": "insurance-life"
			}, {
				"name": "internet-browser"
			}, {
				"name": "inventory"
			}, {
				"name": "ipad"
			}, {
				"name": "ipad-2"
			}, {
				"name": "iphone"
			}, {
				"name": "iphone-2"
			}, {
				"name": "it-host"
			}, {
				"name": "it-instance"
			}, {
				"name": "it-system"
			}, {
				"name": "journey-arrive"
			}, {
				"name": "journey-change"
			}, {
				"name": "journey-depart"
			}, {
				"name": "key"
			}, {
				"name": "kpi-corporate-performance"
			}, {
				"name": "kpi-managing-my-area"
			}, {
				"name": "lab"
			}, {
				"name": "laptop"
			}, {
				"name": "lateness"
			}, {
				"name": "lead"
			}, {
				"name": "lead-outdated"
			}, {
				"name": "leads"
			}, {
				"name": "learning-assistant"
			}, {
				"name": "legend"
			}, {
				"name": "less"
			}, {
				"name": "letter"
			}, {
				"name": "lightbulb"
			}, {
				"name": "line-chart"
			}, {
				"name": "line-chart-dual-axis"
			}, {
				"name": "line-charts"
			}, {
				"name": "list"
			}, {
				"name": "loan"
			}, {
				"name": "locate-me"
			}, {
				"name": "locked"
			}, {
				"name": "log"
			}, {
				"name": "machine"
			}, {
				"name": "manager"
			}, {
				"name": "manager-insight"
			}, {
				"name": "map"
			}, {
				"name": "map-2"
			}, {
				"name": "map-3"
			}, {
				"name": "marketing-campaign"
			}, {
				"name": "meal"
			}, {
				"name": "measure"
			}, {
				"name": "measurement-document"
			}, {
				"name": "measuring-point"
			}, {
				"name": "media-forward"
			}, {
				"name": "media-pause"
			}, {
				"name": "media-play"
			}, {
				"name": "media-reverse"
			}, {
				"name": "media-rewind"
			}, {
				"name": "meeting-room"
			}, {
				"name": "menu"
			}, {
				"name": "menu2"
			}, {
				"name": "message-error"
			}, {
				"name": "message-information"
			}, {
				"name": "message-success"
			}, {
				"name": "message-warning"
			}, {
				"name": "microphone"
			}, {
				"name": "mileage"
			}, {
				"name": "minimize"
			}, {
				"name": "money-bills"
			}, {
				"name": "monitor-payments"
			}, {
				"name": "move"
			}, {
				"name": "mri-scan"
			}, {
				"name": "multi-select"
			}, {
				"name": "multiple-bar-chart"
			}, {
				"name": "multiple-line-chart"
			}, {
				"name": "multiple-pie-chart"
			}, {
				"name": "multiple-radar-chart"
			}, {
				"name": "my-sales-order"
			}, {
				"name": "my-view"
			}, {
				"name": "nav-back"
			}, {
				"name": "navigation-down-arrow"
			}, {
				"name": "navigation-left-arrow"
			}, {
				"name": "navigation-right-arrow"
			}, {
				"name": "navigation-up-arrow"
			}, {
				"name": "negative"
			}, {
				"name": "Netweaver-business-client"
			}, {
				"name": "newspaper"
			}, {
				"name": "notes"
			}, {
				"name": "notification"
			}, {
				"name": "notification-2"
			}, {
				"name": "number-sign"
			}, {
				"name": "nurse"
			}, {
				"name": "nutrition-activity"
			}, {
				"name": "official-service"
			}, {
				"name": "offsite-work"
			}, {
				"name": "open-command-field"
			}, {
				"name": "open-folder"
			}, {
				"name": "opportunities"
			}, {
				"name": "opportunity"
			}, {
				"name": "order-status"
			}, {
				"name": "org-chart"
			}, {
				"name": "outbox"
			}, {
				"name": "outgoing-call"
			}, {
				"name": "overflow"
			}, {
				"name": "overlay"
			}, {
				"name": "overview-chart"
			}, {
				"name": "paging"
			}, {
				"name": "paid-leave"
			}, {
				"name": "palette"
			}, {
				"name": "paper-plane"
			}, {
				"name": "passenger-train"
			}, {
				"name": "past"
			}, {
				"name": "pause"
			}, {
				"name": "payment-approval"
			}, {
				"name": "pdf-attachment"
			}, {
				"name": "pdf-reader"
			}, {
				"name": "pending"
			}, {
				"name": "per-diem"
			}, {
				"name": "performance"
			}, {
				"name": "permission"
			}, {
				"name": "person-placeholder"
			}, {
				"name": "personnel-view"
			}, {
				"name": "pharmacy"
			}, {
				"name": "phone"
			}, {
				"name": "photo-voltaic"
			}, {
				"name": "physical-activity"
			}, {
				"name": "picture"
			}, {
				"name": "pie-chart"
			}, {
				"name": "pipeline-analysis"
			}, {
				"name": "play"
			}, {
				"name": "pool"
			}, {
				"name": "popup-window"
			}, {
				"name": "positive"
			}, {
				"name": "post"
			}, {
				"name": "ppt-attachment"
			}, {
				"name": "present"
			}, {
				"name": "print"
			}, {
				"name": "private"
			}, {
				"name": "process"
			}, {
				"name": "product"
			}, {
				"name": "projector"
			}, {
				"name": "provision"
			}, {
				"name": "pull-down"
			}, {
				"name": "pushpin-off"
			}, {
				"name": "pushpin-on"
			}, {
				"name": "puzzle"
			}, {
				"name": "quality-issue"
			}, {
				"name": "question-mark"
			}, {
				"name": "radar-chart"
			}, {
				"name": "receipt"
			}, {
				"name": "record"
			}, {
				"name": "redo"
			}, {
				"name": "refresh"
			}, {
				"name": "repost"
			}, {
				"name": "request"
			}, {
				"name": "resize"
			}, {
				"name": "resize-horizontal"
			}, {
				"name": "resize-vertical"
			}, {
				"name": "response"
			}, {
				"name": "restart"
			}, {
				"name": "retail-store"
			}, {
				"name": "retail-store-manager"
			}, {
				"name": "role"
			}, {
				"name": "sales-document"
			}, {
				"name": "sales-notification"
			}, {
				"name": "sales-order"
			}, {
				"name": "sales-order-item"
			}, {
				"name": "sales-quote"
			}, {
				"name": "sap-box"
			}, {
				"name": "sap-logo-shape"
			}, {
				"name": "save"
			}, {
				"name": "scatter-chart"
			}, {
				"name": "search"
			}, {
				"name": "settings"
			}, {
				"name": "share"
			}, {
				"name": "share-2"
			}, {
				"name": "shelf"
			}, {
				"name": "shield"
			}, {
				"name": "shipping-status"
			}, {
				"name": "shortcut"
			}, {
				"name": "show"
			}, {
				"name": "signature"
			}, {
				"name": "simple-payment"
			}, {
				"name": "simulate"
			}, {
				"name": "slim-arrow-down"
			}, {
				"name": "slim-arrow-left"
			}, {
				"name": "slim-arrow-right"
			}, {
				"name": "slim-arrow-up"
			}, {
				"name": "soccor"
			}, {
				"name": "sonography"
			}, {
				"name": "sort"
			}, {
				"name": "sort-ascending"
			}, {
				"name": "sort-descending"
			}, {
				"name": "sorting-ranking"
			}, {
				"name": "status-completed"
			}, {
				"name": "status-critical"
			}, {
				"name": "status-error"
			}, {
				"name": "status-in-process"
			}, {
				"name": "status-inactive"
			}, {
				"name": "status-negative"
			}, {
				"name": "status-positive"
			}, {
				"name": "step"
			}, {
				"name": "stethoscope"
			}, {
				"name": "stop"
			}, {
				"name": "study-leave"
			}, {
				"name": "subway-train"
			}, {
				"name": "suitcase"
			}, {
				"name": "supplier"
			}, {
				"name": "survey"
			}, {
				"name": "switch-classes"
			}, {
				"name": "switch-views"
			}, {
				"name": "synchronize"
			}, {
				"name": "syntax"
			}, {
				"name": "syringe"
			}, {
				"name": "sys-add"
			}, {
				"name": "sys-back"
			}, {
				"name": "sys-back-2"
			}, {
				"name": "sys-cancel"
			}, {
				"name": "sys-cancel-2"
			}, {
				"name": "sys-enter"
			}, {
				"name": "sys-enter-2"
			}, {
				"name": "sys-find"
			}, {
				"name": "sys-find-next"
			}, {
				"name": "sys-first-page"
			}, {
				"name": "sys-help"
			}, {
				"name": "sys-help-2"
			}, {
				"name": "sys-last-page"
			}, {
				"name": "sys-minus"
			}, {
				"name": "sys-monitor"
			}, {
				"name": "sys-next-page"
			}, {
				"name": "sys-prev-page"
			}, {
				"name": "system-exit"
			}, {
				"name": "system-exit-2"
			}, {
				"name": "table-chart"
			}, {
				"name": "table-view"
			}, {
				"name": "tag"
			}, {
				"name": "tag-cloud-chart"
			}, {
				"name": "tags"
			}, {
				"name": "target-group"
			}, {
				"name": "task"
			}, {
				"name": "taxi"
			}, {
				"name": "technical-object"
			}, {
				"name": "temperature"
			}, {
				"name": "theater"
			}, {
				"name": "thing-type"
			}, {
				"name": "time-account"
			}, {
				"name": "time-entry-request"
			}, {
				"name": "time-overtime"
			}, {
				"name": "timesheet"
			}, {
				"name": "to-be-reviewed"
			}, {
				"name": "toaster-down"
			}, {
				"name": "toaster-top"
			}, {
				"name": "toaster-up"
			}, {
				"name": "tools-opportunity"
			}, {
				"name": "travel-expense"
			}, {
				"name": "travel-expense-report"
			}, {
				"name": "travel-itinerary"
			}, {
				"name": "travel-request"
			}, {
				"name": "tree"
			}, {
				"name": "trip-report"
			}, {
				"name": "umbrella"
			}, {
				"name": "undo"
			}, {
				"name": "unfavorite"
			}, {
				"name": "unlocked"
			}, {
				"name": "unpaid-leave"
			}, {
				"name": "unwired"
			}, {
				"name": "up"
			}, {
				"name": "upload"
			}, {
				"name": "upstacked-chart"
			}, {
				"name": "value-help"
			}, {
				"name": "vds-file"
			}, {
				"name": "vehicle-repair"
			}, {
				"name": "vertical-bar-chart"
			}, {
				"name": "vertical-bar-chart-2"
			}, {
				"name": "vertical-grip"
			}, {
				"name": "vertical-stacked-chart"
			}, {
				"name": "video"
			}, {
				"name": "visits"
			}, {
				"name": "waiver"
			}, {
				"name": "wallet"
			}, {
				"name": "warning"
			}, {
				"name": "warning2"
			}, {
				"name": "washing-machine"
			}, {
				"name": "weather-proofing"
			}, {
				"name": "web-cam"
			}, {
				"name": "widgets"
			}, {
				"name": "windows-doors"
			}, {
				"name": "work-history"
			}, {
				"name": "workflow-tasks"
			}, {
				"name": "world"
			}, {
				"name": "wounds-doc"
			}, {
				"name": "wrench"
			}, {
				"name": "x-ray"
			}, {
				"name": "zoom-in"
			}, {
				"name": "zoom-out"
			}],
			"count": 535
		}, {
			"name": "action",
			"text": "Actions",
			"icons": [{
				"name": "accept"
			}, {
				"name": "action"
			}, {
				"name": "action-settings"
			}, {
				"name": "activate"
			}, {
				"name": "add"
			}, {
				"name": "add-filter"
			}, {
				"name": "add-process"
			}, {
				"name": "back-to-top"
			}, {
				"name": "begin"
			}, {
				"name": "bookmark"
			}, {
				"name": "cancel-maintenance"
			}, {
				"name": "collapse-group"
			}, {
				"name": "comment"
			}, {
				"name": "complete"
			}, {
				"name": "decline"
			}, {
				"name": "delete"
			}, {
				"name": "display"
			}, {
				"name": "down"
			}, {
				"name": "download"
			}, {
				"name": "drill-down"
			}, {
				"name": "drill-up"
			}, {
				"name": "dropdown"
			}, {
				"name": "duplicate"
			}, {
				"name": "edit"
			}, {
				"name": "edit-outside"
			}, {
				"name": "email"
			}, {
				"name": "exit-full-screen"
			}, {
				"name": "expand-group"
			}, {
				"name": "favorite"
			}, {
				"name": "feed"
			}, {
				"name": "filter"
			}, {
				"name": "flag"
			}, {
				"name": "home"
			}, {
				"name": "less"
			}, {
				"name": "locked"
			}, {
				"name": "log"
			}, {
				"name": "media-forward"
			}, {
				"name": "media-pause"
			}, {
				"name": "media-play"
			}, {
				"name": "media-reverse"
			}, {
				"name": "media-rewind"
			}, {
				"name": "menu2"
			}, {
				"name": "minimize"
			}, {
				"name": "move"
			}, {
				"name": "multi-select"
			}, {
				"name": "overflow"
			}, {
				"name": "pause"
			}, {
				"name": "play"
			}, {
				"name": "post"
			}, {
				"name": "record"
			}, {
				"name": "redo"
			}, {
				"name": "refresh"
			}, {
				"name": "resize"
			}, {
				"name": "resize-horizontal"
			}, {
				"name": "resize-vertical"
			}, {
				"name": "response"
			}, {
				"name": "restart"
			}, {
				"name": "save"
			}, {
				"name": "search"
			}, {
				"name": "share"
			}, {
				"name": "shield"
			}, {
				"name": "shortcut"
			}, {
				"name": "sort"
			}, {
				"name": "sort-ascending"
			}, {
				"name": "sort-descending"
			}, {
				"name": "stop"
			}, {
				"name": "synchronize"
			}, {
				"name": "sys-add"
			}, {
				"name": "sys-cancel"
			}, {
				"name": "sys-cancel-2"
			}, {
				"name": "sys-find"
			}, {
				"name": "sys-minus"
			}, {
				"name": "undo"
			}, {
				"name": "unfavorite"
			}, {
				"name": "unlocked"
			}, {
				"name": "up"
			}, {
				"name": "upload"
			}, {
				"name": "value-help"
			}, {
				"name": "wrench"
			}, {
				"name": "zoom-in"
			}, {
				"name": "zoom-out"
			}],
			"count": 81
		}, {
			"name": "arrow",
			"text": "Arrows",
			"icons": [{
				"name": "arrow-bottom"
			}, {
				"name": "arrow-down"
			}, {
				"name": "arrow-left"
			}, {
				"name": "arrow-right"
			}, {
				"name": "arrow-top"
			}, {
				"name": "cause"
			}, {
				"name": "chart-axis"
			}, {
				"name": "close-command-field"
			}, {
				"name": "collapse-group"
			}, {
				"name": "down"
			}, {
				"name": "download"
			}, {
				"name": "enter-more"
			}, {
				"name": "expand-group"
			}, {
				"name": "feeder-arrow"
			}, {
				"name": "forward"
			}, {
				"name": "full-screen"
			}, {
				"name": "initiative"
			}, {
				"name": "inspect"
			}, {
				"name": "locate-me"
			}, {
				"name": "media-forward"
			}, {
				"name": "media-play"
			}, {
				"name": "media-reverse"
			}, {
				"name": "move"
			}, {
				"name": "nav-back"
			}, {
				"name": "navigation-down-arrow"
			}, {
				"name": "navigation-left-arrow"
			}, {
				"name": "navigation-right-arrow"
			}, {
				"name": "navigation-up-arrow"
			}, {
				"name": "open-command-field"
			}, {
				"name": "play"
			}, {
				"name": "process"
			}, {
				"name": "pull-down"
			}, {
				"name": "redo"
			}, {
				"name": "refresh"
			}, {
				"name": "repost"
			}, {
				"name": "resize"
			}, {
				"name": "response"
			}, {
				"name": "share"
			}, {
				"name": "shortcut"
			}, {
				"name": "slim-arrow-down"
			}, {
				"name": "slim-arrow-left"
			}, {
				"name": "slim-arrow-right"
			}, {
				"name": "slim-arrow-up"
			}, {
				"name": "sort"
			}, {
				"name": "sort-ascending"
			}, {
				"name": "sort-descending"
			}, {
				"name": "sorting-ranking"
			}, {
				"name": "step"
			}, {
				"name": "synchronize"
			}, {
				"name": "sys-back"
			}, {
				"name": "sys-back-2"
			}, {
				"name": "undo"
			}, {
				"name": "upload"
			}],
			"count": 53
		}, {
			"name": "calendar",
			"text": "Calendars",
			"icons": [{
				"name": "appointment"
			}, {
				"name": "appointment-2"
			}, {
				"name": "calendar"
			}, {
				"name": "gantt-bars"
			}, {
				"name": "measurement-document"
			}, {
				"name": "notes"
			}, {
				"name": "per-diem"
			}],
			"count": 7
		}, {
			"name": "callout",
			"text": "Callout",
			"icons": [{
				"name": "discussion"
			}, {
				"name": "discussion-2"
			}, {
				"name": "hello-world"
			}, {
				"name": "notification-2"
			}, {
				"name": "post"
			}, {
				"name": "sales-notification"
			}, {
				"name": "tag-cloud-chart"
			}, {
				"name": "thing-type"
			}, {
				"name": "travel-request"
			}],
			"count": 9
		}, {
			"name": "charts",
			"text": "Charts",
			"icons": [{
				"name": "along-stacked-chart"
			}, {
				"name": "area-chart"
			}, {
				"name": "bar-chart"
			}, {
				"name": "bubble-chart"
			}, {
				"name": "chart-axis"
			}, {
				"name": "choropleth-chart"
			}, {
				"name": "column-chart-dual-axis"
			}, {
				"name": "crossed-line-chart"
			}, {
				"name": "full-stacked-chart"
			}, {
				"name": "full-stacked-column-chart"
			}, {
				"name": "gantt-bars"
			}, {
				"name": "geographic-bubble-chart"
			}, {
				"name": "horizontal-bar-chart"
			}, {
				"name": "horizontal-bar-chart-2"
			}, {
				"name": "horizontal-stacked-chart"
			}, {
				"name": "legend"
			}, {
				"name": "line-chart"
			}, {
				"name": "line-chart-dual-axis"
			}, {
				"name": "line-charts"
			}, {
				"name": "multiple-bar-chart"
			}, {
				"name": "multiple-line-chart"
			}, {
				"name": "multiple-pie-chart"
			}, {
				"name": "multiple-radar-chart"
			}, {
				"name": "org-chart"
			}, {
				"name": "overview-chart"
			}, {
				"name": "pie-chart"
			}, {
				"name": "radar-chart"
			}, {
				"name": "scatter-chart"
			}, {
				"name": "table-chart"
			}, {
				"name": "tag-cloud-chart"
			}, {
				"name": "upstacked-chart"
			}, {
				"name": "vertical-bar-chart"
			}, {
				"name": "vertical-bar-chart-2"
			}, {
				"name": "vertical-stacked-chart"
			}],
			"count": 34
		}, {
			"name": "clipboard",
			"text": "Clipboards",
			"icons": [{
				"name": "activity-2"
			}, {
				"name": "activity-assigned-to-goal"
			}, {
				"name": "activity-individual"
			}, {
				"name": "activity-items"
			}, {
				"name": "add-activity-2"
			}, {
				"name": "clinical-tast-tracker"
			}, {
				"name": "crm-service-manager"
			}, {
				"name": "task"
			}, {
				"name": "workflow-tasks"
			}],
			"count": 9
		}, {
			"name": "devices",
			"text": "Devices",
			"icons": [{
				"name": "dishwasher"
			}, {
				"name": "fax-machine"
			}, {
				"name": "fob-watch"
			}, {
				"name": "fridge"
			}, {
				"name": "ipad"
			}, {
				"name": "ipad-2"
			}, {
				"name": "iphone"
			}, {
				"name": "iphone-2"
			}, {
				"name": "laptop"
			}, {
				"name": "machine"
			}, {
				"name": "marketing-campaign"
			}, {
				"name": "microphone"
			}, {
				"name": "phone"
			}, {
				"name": "print"
			}, {
				"name": "projector"
			}, {
				"name": "simulate"
			}, {
				"name": "sys-monitor"
			}, {
				"name": "video"
			}, {
				"name": "washing-machine"
			}, {
				"name": "web-cam"
			}],
			"count": 20
		}, {
			"name": "doc",
			"text": "Documents",
			"icons": [{
				"name": "attachment-audio"
			}, {
				"name": "attachment-e-pub"
			}, {
				"name": "attachment-html"
			}, {
				"name": "attachment-photo"
			}, {
				"name": "attachment-text-file"
			}, {
				"name": "attachment-video"
			}, {
				"name": "attachment-zip-file"
			}, {
				"name": "course-program"
			}, {
				"name": "create"
			}, {
				"name": "customer-financial-fact-sheet"
			}, {
				"name": "doc-attachment"
			}, {
				"name": "document"
			}, {
				"name": "document-text"
			}, {
				"name": "documents"
			}, {
				"name": "excel-attachment"
			}, {
				"name": "expense-report"
			}, {
				"name": "inspection"
			}, {
				"name": "insurance-car"
			}, {
				"name": "insurance-house"
			}, {
				"name": "insurance-life"
			}, {
				"name": "measurement-document"
			}, {
				"name": "my-sales-order"
			}, {
				"name": "newspaper"
			}, {
				"name": "order-status"
			}, {
				"name": "pdf-attachment"
			}, {
				"name": "permission"
			}, {
				"name": "ppt-attachment"
			}, {
				"name": "pushpin-on"
			}, {
				"name": "sales-document"
			}, {
				"name": "sales-order"
			}, {
				"name": "sales-order-item"
			}, {
				"name": "sales-quote"
			}, {
				"name": "sys-first-page"
			}, {
				"name": "sys-last-page"
			}, {
				"name": "sys-next-page"
			}, {
				"name": "sys-prev-page"
			}, {
				"name": "timesheet"
			}, {
				"name": "vds-file"
			}],
			"count": 38
		}, {
			"name": "folder",
			"text": "Folder",
			"icons": [{
				"name": "curriculum"
			}, {
				"name": "fallback"
			}, {
				"name": "folder"
			}, {
				"name": "folder-blank"
			}, {
				"name": "folder-full"
			}, {
				"name": "open-folder"
			}, {
				"name": "work-history"
			}],
			"count": 7
		}, {
			"name": "med",
			"text": "Medical",
			"icons": [{
				"name": "accidental-leave"
			}, {
				"name": "bed"
			}, {
				"name": "clinical-order"
			}, {
				"name": "electrocardiogram"
			}, {
				"name": "electronic-medical-record"
			}, {
				"name": "endoscopy"
			}, {
				"name": "nurse"
			}, {
				"name": "pharmacy"
			}, {
				"name": "sonography"
			}, {
				"name": "stethoscope"
			}, {
				"name": "syringe"
			}, {
				"name": "wounds-doc"
			}],
			"count": 12
		}, {
			"name": "money",
			"text": "Money",
			"icons": [{
				"name": "capital-projects"
			}, {
				"name": "collections-insight"
			}, {
				"name": "commission-check"
			}, {
				"name": "customer-financial-fact-sheet"
			}, {
				"name": "expense-report"
			}, {
				"name": "lead-outdated"
			}, {
				"name": "loan"
			}, {
				"name": "money-bills"
			}, {
				"name": "monitor-payments"
			}, {
				"name": "paid-leave"
			}, {
				"name": "payment-approval"
			}, {
				"name": "per-diem"
			}, {
				"name": "sales-document"
			}, {
				"name": "sales-notification"
			}, {
				"name": "sales-order"
			}, {
				"name": "sales-order-item"
			}, {
				"name": "sales-quote"
			}, {
				"name": "simple-payment"
			}, {
				"name": "time-overtime"
			}, {
				"name": "travel-expense-report"
			}, {
				"name": "unpaid-leave"
			}, {
				"name": "waiver"
			}],
			"count": 22
		}, {
			"name": "people",
			"text": "People",
			"icons": [{
				"name": "activity-individual"
			}, {
				"name": "citizen-connect"
			}, {
				"name": "collaborate"
			}, {
				"name": "company-view"
			}, {
				"name": "customer"
			}, {
				"name": "customer-and-supplier"
			}, {
				"name": "customer-history"
			}, {
				"name": "doctor"
			}, {
				"name": "employee"
			}, {
				"name": "employee-approvals"
			}, {
				"name": "employee-lookup"
			}, {
				"name": "employee-pane"
			}, {
				"name": "employee-rejections"
			}, {
				"name": "family-care"
			}, {
				"name": "family-protection"
			}, {
				"name": "group"
			}, {
				"name": "hr-approval"
			}, {
				"name": "idea-wall"
			}, {
				"name": "kpi-managing-my-area"
			}, {
				"name": "leads"
			}, {
				"name": "learning-assistant"
			}, {
				"name": "manager"
			}, {
				"name": "my-view"
			}, {
				"name": "nurse"
			}, {
				"name": "opportunities"
			}, {
				"name": "person-placeholder"
			}, {
				"name": "physical-activity"
			}, {
				"name": "role"
			}, {
				"name": "supplier"
			}, {
				"name": "wounds-doc"
			}],
			"count": 30
		}, {
			"name": "place",
			"text": "Places",
			"icons": [{
				"name": "building"
			}, {
				"name": "doctor"
			}, {
				"name": "factory"
			}, {
				"name": "globe"
			}, {
				"name": "meal"
			}, {
				"name": "mileage"
			}, {
				"name": "official-service"
			}, {
				"name": "offsite-work"
			}, {
				"name": "retail-store"
			}, {
				"name": "theater"
			}, {
				"name": "world"
			}],
			"count": 11
		}, {
			"name": "shop",
			"text": "Shopping",
			"icons": [{
				"name": "basket"
			}, {
				"name": "cart"
			}, {
				"name": "cart-2"
			}, {
				"name": "cart-3"
			}, {
				"name": "cart-4"
			}, {
				"name": "cart-5"
			}, {
				"name": "cart-approval"
			}, {
				"name": "cart-full"
			}, {
				"name": "retail-store"
			}, {
				"name": "retail-store-manager"
			}],
			"count": 10
		}, {
			"name": "status",
			"text": "Status",
			"icons": [{
				"name": "accidental-leave"
			}, {
				"name": "alert"
			}, {
				"name": "badge"
			}, {
				"name": "bookmark"
			}, {
				"name": "connected"
			}, {
				"name": "decision"
			}, {
				"name": "disconnected"
			}, {
				"name": "employee-approvals"
			}, {
				"name": "flag"
			}, {
				"name": "goal"
			}, {
				"name": "goalseek"
			}, {
				"name": "history"
			}, {
				"name": "incident"
			}, {
				"name": "lab"
			}, {
				"name": "lateness"
			}, {
				"name": "lead"
			}, {
				"name": "lead-outdated"
			}, {
				"name": "locked"
			}, {
				"name": "message-error"
			}, {
				"name": "message-information"
			}, {
				"name": "message-success"
			}, {
				"name": "message-warning"
			}, {
				"name": "notification"
			}, {
				"name": "question-mark"
			}, {
				"name": "status-completed"
			}, {
				"name": "status-critical"
			}, {
				"name": "status-error"
			}, {
				"name": "status-in-process"
			}, {
				"name": "status-inactive"
			}, {
				"name": "status-negative"
			}, {
				"name": "status-positive"
			}, {
				"name": "sys-cancel"
			}, {
				"name": "sys-enter"
			}, {
				"name": "sys-enter-2"
			}, {
				"name": "sys-help"
			}, {
				"name": "sys-help-2"
			}, {
				"name": "target-group"
			}, {
				"name": "temperature"
			}, {
				"name": "to-be-reviewed"
			}, {
				"name": "unlocked"
			}, {
				"name": "warning"
			}, {
				"name": "warning2"
			}],
			"count": 42
		}, {
			"name": "thing",
			"text": "Things",
			"icons": [{
				"name": "basket"
			}, {
				"name": "bed"
			}, {
				"name": "calendar"
			}, {
				"name": "camera"
			}, {
				"name": "cart"
			}, {
				"name": "compare-2"
			}, {
				"name": "competitor"
			}, {
				"name": "course-book"
			}, {
				"name": "database"
			}, {
				"name": "dishwasher"
			}, {
				"name": "display"
			}, {
				"name": "e-care"
			}, {
				"name": "education"
			}, {
				"name": "energy-saving-lightbulb"
			}, {
				"name": "eraser"
			}, {
				"name": "explorer"
			}, {
				"name": "fridge"
			}, {
				"name": "ipad"
			}, {
				"name": "ipad-2"
			}, {
				"name": "iphone"
			}, {
				"name": "iphone-2"
			}, {
				"name": "key"
			}, {
				"name": "lab"
			}, {
				"name": "laptop"
			}, {
				"name": "machine"
			}, {
				"name": "marketing-campaign"
			}, {
				"name": "meal"
			}, {
				"name": "microphone"
			}, {
				"name": "mileage"
			}, {
				"name": "nutrition-activity"
			}, {
				"name": "palette"
			}, {
				"name": "paper-plane"
			}, {
				"name": "pharmacy"
			}, {
				"name": "phone"
			}, {
				"name": "picture"
			}, {
				"name": "post"
			}, {
				"name": "projector"
			}, {
				"name": "puzzle"
			}, {
				"name": "simulate"
			}, {
				"name": "soccor"
			}, {
				"name": "stethoscope"
			}, {
				"name": "study-leave"
			}, {
				"name": "suitcase"
			}, {
				"name": "sys-find"
			}, {
				"name": "sys-monitor"
			}, {
				"name": "tags"
			}, {
				"name": "temperature"
			}, {
				"name": "umbrella"
			}, {
				"name": "video"
			}, {
				"name": "wallet"
			}, {
				"name": "washing-machine"
			}, {
				"name": "web-cam"
			}, {
				"name": "wrench"
			}],
			"count": 53
		}, {
			"name": "time",
			"text": "Time",
			"icons": [{
				"name": "create-entry-time"
			}, {
				"name": "customer-history"
			}, {
				"name": "fob-watch"
			}, {
				"name": "future"
			}, {
				"name": "history"
			}, {
				"name": "instance"
			}, {
				"name": "lateness"
			}, {
				"name": "past"
			}, {
				"name": "pending"
			}, {
				"name": "present"
			}, {
				"name": "time-entry-request"
			}, {
				"name": "time-overtime"
			}, {
				"name": "timesheet"
			}],
			"count": 13
		}, {
			"name": "travel",
			"text": "Travel",
			"icons": [{
				"name": "bed"
			}, {
				"name": "bus-public-transport"
			}, {
				"name": "car-rental"
			}, {
				"name": "cargo-train"
			}, {
				"name": "doctor"
			}, {
				"name": "flight"
			}, {
				"name": "home"
			}, {
				"name": "meal"
			}, {
				"name": "passenger-train"
			}, {
				"name": "physical-activity"
			}, {
				"name": "shipping-status"
			}, {
				"name": "subway-train"
			}, {
				"name": "suitcase"
			}, {
				"name": "taxi"
			}, {
				"name": "travel-expense"
			}, {
				"name": "travel-itinerary"
			}, {
				"name": "world"
			}],
			"count": 17
		}]
	},


};